name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm install
        working-directory: server

      - name: Create server/.env with secrets
        run: |
          echo "PORT=${{ secrets.PORT }}" >> server/.env
          echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> server/.env
          echo "VITE_LOG_LEVEL=${{ secrets.VITE_LOG_LEVEL }}" >> server/.env
          echo "DB_STRING='${{ secrets.DB_STRING }}'" >> server/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> server/.env
          echo "PUB_KEY='${{ secrets.PUB_KEY }}'" >> server/.env
          echo "PRIVATE_KEY='${{ secrets.PRIVATE_KEY }}'" >> server/.env
          echo "API_URL=${{ secrets.API_URL }}" >> server/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> server/.env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> server/.env
          echo "VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }}" >> server/.env
          echo "allowedOrigins='${{ secrets.allowedOrigins }}'" >> server/.env

      - name: Deploy server folder to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/**"
          target: "/home/ec2-user/whiteboard/server"

      - name: SSH into EC2 and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/whiteboard/server
            npm install

